"""Bake the standalone frontend's static data from real artifacts.

Writes two committed files so the deployed site needs no Python and no dataset:

  frontend/data/points.bin    flat Float32Array, [x, y, z, label] per point
  frontend/data/snapshot.json measured metrics, split geometry, demo decisions

SPENDS NOTHING. The only assemblers this module can reach are
`assemble_deterministic` and the fault-injection wrapper below, both of which
are pure local code. `assemble()` is never called, so the provider seam that
resolves ANTHROPIC_API_KEY is never entered. `main()` additionally strips both
provider keys out of the environment before doing any work, so even a future
edit that reached the default path would fall back to templates rather than
bill. Importing `dispute_autopilot` loads .env, which on this machine DOES put a
live key in the environment -- that is exactly why the strip is here and not a
comment saying "be careful".

Every number in this file is copied or measured. Nothing is asserted.
"""
import json
import os
from datetime import datetime, timezone

import numpy as np
import pandas as pd

from dispute_autopilot.assembler.assemble import assemble_deterministic
from dispute_autopilot.casefile.store import VaultStore, choose_posture
from dispute_autopilot.casefile.synthesize import synthesize_casefile
from dispute_autopilot.config import SITE_DATA_DIR
from dispute_autopilot.contracts import Claim, Dispute, EvidenceBundle
from dispute_autopilot.economics.cost_model import to_inr
from dispute_autopilot.ingest.load import load_raw
from dispute_autopilot.ingest.split import CALIB_FRAC, TRAIN_FRAC, temporal_split
from dispute_autopilot.model.predict import Scorer
from dispute_autopilot.triage import triage
from eval import REPORTS

N_SAMPLE = 100_000

# Proportional allocation already yields ~3,500 positives at a 3.5% base rate,
# so this floor does not bind today. It exists so that a future re-run on a
# smaller or less positive frame cannot silently ship a cloud with no fraud in
# it -- the whole point of colouring by the label is that both classes are there.
MIN_POSITIVES = 3_000
SAMPLE_SEED = 20260904

# The site plots these; it does not fit them. 200 points draw a PR curve that is
# visually indistinguishable from the full array at any sane figure size.
MAX_CURVE_POINTS = 200

# Must match ui/app.py and eval/find_demo_rows.py. A demo row index is only
# meaningful against the frame it was found in.
DEMO_SAMPLE_N = 5_000
REASON = "fraud_card_absent"

# Row indices into load_raw(sample_n=DEMO_SAMPLE_N), regenerated by
# `python -m eval.find_demo_rows`.
#
# accept is None ON PURPOSE. As of 2026-09-04 no ACCEPT decision is reachable
# anywhere in the 590,540 rows: 605 rows sit inside the ACCEPT economic window
# (ACTIVE posture, delta EV below the negative margin) and every one of them is
# ProductCD C or S, which never carries M1/M2/M6. No AVS flags means
# synthesize_casefile files no billing_proof, billing_proof is required for
# fraud_card_absent, and the required-evidence gate forces REVIEW before
# economics is ever consulted. docs/VIDEO-SCRIPT.md and docs/SESSION-HANDOFF.md
# still name row 780 as the ACCEPT demo; it now decides REVIEW. Rather than
# fabricate a case, this exporter writes cases.accept = null and says why in
# notes.accept_case.
DEMO_ROWS: dict[str, int | None] = {"contest": 7, "accept": None, "review": 0}
EXPECTED_ACTION = {"contest": "CONTEST", "accept": "ACCEPT", "review": "REVIEW"}

# Mirrors the fault-injection assembler defined inline in ui/app.py. That one is
# a closure inside a Streamlit script and cannot be imported without starting
# Streamlit, so the literal is duplicated here and tests/test_site_data.py
# asserts both copies still carry it. Change one, change the other.
FABRICATED_AWB = "Delivered under AWB ZZZ999"


def assemble_with_fabricated_claim(dispute: Dispute, casefile) -> EvidenceBundle:
    """Assert a tracking number that appears nowhere in the vault.

    The refusal payload the site animates has to come from the gate actually
    firing. This is the same fire drill the Streamlit demo offers: real
    assembly, one invented identifier bolted on, then the real verifier and the
    real refusal gate decide what happens to it.
    """
    real = assemble_deterministic(dispute, casefile)
    return EvidenceBundle(
        dispute_id=dispute.dispute_id,
        fields=dict(real.fields, shipping_proof=FABRICATED_AWB),
        claims=list(real.claims)
        + [Claim(text=FABRICATED_AWB, source_field="carrier_tracking")],
    )


def _jsonable(value):
    """One raw feature value, rendered so json.dumps accepts it.

    NaN is emitted as null, never as the float nan that json.dumps would happily
    write and no JSON parser will read back.
    """
    if value is None:
        return None
    try:
        if pd.isna(value):
            return None
    except (TypeError, ValueError):
        pass
    if isinstance(value, np.bool_):
        return bool(value)
    if isinstance(value, np.integer):
        return int(value)
    if isinstance(value, np.floating):
        return float(value)
    if isinstance(value, (str, bool, int, float)):
        return value
    return str(value)


def _downsample(xs, ys, limit: int = MAX_CURVE_POINTS) -> list[list[float]]:
    n = len(xs)
    keep = (
        range(n) if n <= limit
        else np.unique(np.linspace(0, n - 1, limit).round().astype(int))
    )
    return [[round(float(xs[i]), 6), round(float(ys[i]), 6)] for i in keep]


def _stratified_sample(labels: np.ndarray) -> tuple[np.ndarray, dict]:
    """Proportional allocation on isFraud, with a floor on the positive class.

    Uniform sampling would keep the base rate but the site states the method
    next to the picture, so the method has to be recorded rather than described
    from memory later.
    """
    rng = np.random.default_rng(SAMPLE_SEED)
    pos = np.flatnonzero(labels == 1.0)
    neg = np.flatnonzero(labels == 0.0)

    proportional = int(round(N_SAMPLE * len(pos) / len(labels)))
    n_pos = min(len(pos), max(proportional, MIN_POSITIVES))
    n_neg = min(len(neg), N_SAMPLE - n_pos)

    idx = np.concatenate([
        rng.choice(pos, size=n_pos, replace=False),
        rng.choice(neg, size=n_neg, replace=False),
    ])
    idx.sort()   # keep temporal order: the frame is sorted by TransactionDT

    return idx, {
        "method": "stratified on isFraud, proportional allocation "
                  "with a floor on the positive class, sampled without replacement",
        "seed": SAMPLE_SEED,
        "minimum_positives": MIN_POSITIVES,
        "floor_binding": bool(n_pos > proportional),
        "n_positive_total": int(len(pos)),
        "n_negative_total": int(len(neg)),
        "n_positive_sampled": int(n_pos),
        "n_negative_sampled": int(n_neg),
        "positive_rate_full": float(len(pos) / len(labels)),
        "positive_rate_sampled": float(n_pos / (n_pos + n_neg)),
    }


def _case(label: str, row_index: int, data: pd.DataFrame, scorer, vault) -> dict:
    """One demo row driven through the real triage path, deterministic assembler."""
    row = data.iloc[[row_index]]
    amount = float(to_inr(row["TransactionAmt"].iloc[0]))
    score = scorer.score_one(row)
    posture = choose_posture(score.p_chargeback, amount)
    casefile = synthesize_casefile(row.iloc[0], posture, seed=row_index)
    vault.put(casefile)

    dispute = Dispute(
        dispute_id=f"disp_{row_index}",
        transaction_id=int(row["TransactionID"].iloc[0]),
        amount_inr=amount,
        reason_code=REASON,
    )
    decision = triage(dispute, row, scorer, vault, assemble_deterministic)
    if decision.action.value != EXPECTED_ACTION[label]:
        raise SystemExit(
            f"row {row_index} was expected to decide {EXPECTED_ACTION[label]} "
            f"and decided {decision.action.value}. The demo rows have drifted; "
            f"regenerate them with `python -m eval.find_demo_rows` and fix "
            f"DEMO_ROWS rather than shipping a mislabelled case."
        )

    features = {k: _jsonable(v) for k, v in row.iloc[0].to_dict().items()}
    # The API hands `features` straight back to POST /disputes/{id}/triage, so
    # it has to score identically after the JSON round trip. Checked, not hoped.
    replayed = scorer.score_one(pd.DataFrame([features])).p_chargeback
    if abs(replayed - score.p_chargeback) > 1e-9:
        raise SystemExit(
            f"row {row_index} scores {score.p_chargeback} from the dataframe and "
            f"{replayed} from its serialised feature dict. /demo/cases would hand "
            f"the browser a payload that does not reproduce this decision."
        )

    return {
        "row": row_index,
        "dispute_id": dispute.dispute_id,
        "transaction_id": dispute.transaction_id,
        "amount_inr": amount,
        "reason_code": REASON,
        "posture": posture.value,
        "p_chargeback": score.p_chargeback,
        "top_reasons": [list(r) for r in score.top_reasons],
        "features": features,
        "decision": decision.model_dump(mode="json"),
        "casefile": casefile.model_dump(mode="json"),
        "bundle": decision.bundle.model_dump(mode="json") if decision.bundle else None,
    }


def _refusal(row_index: int, data: pd.DataFrame, scorer, vault) -> dict:
    """The same row, assembled twice: once honestly, once with one invented AWB."""
    row = data.iloc[[row_index]]
    amount = float(to_inr(row["TransactionAmt"].iloc[0]))
    score = scorer.score_one(row)
    posture = choose_posture(score.p_chargeback, amount)
    casefile = synthesize_casefile(row.iloc[0], posture, seed=row_index)
    vault.put(casefile)
    dispute = Dispute(dispute_id=f"disp_{row_index}", amount_inr=amount,
                      transaction_id=int(row["TransactionID"].iloc[0]),
                      reason_code=REASON)

    before = triage(dispute, row, scorer, vault, assemble_deterministic)
    after = triage(dispute, row, scorer, vault, assemble_with_fabricated_claim)

    if before.action.value != "CONTEST" or after.action.value != "REVIEW":
        raise SystemExit(
            f"the refusal gate did not fire on row {row_index}: "
            f"{before.action.value} -> {after.action.value}, expected CONTEST -> "
            f"REVIEW. Section 8 of the site claims this happens; do not ship the "
            f"claim without the behaviour."
        )

    return {
        "row": row_index,
        "casefile": casefile.model_dump(mode="json"),
        "claims": [c.model_dump(mode="json") for c in after.bundle.claims],
        "fabricated_claim": FABRICATED_AWB,
        "refused_claims": after.refused_claims,
        "groundedness": after.bundle.groundedness,
        "before": before.action.value,
        "after": after.action.value,
    }


def main() -> dict:
    # Belt and braces on the zero-spend guarantee -- see the module docstring.
    os.environ.pop("ANTHROPIC_API_KEY", None)
    os.environ.pop("OPENAI_API_KEY", None)

    scorer = Scorer.load()
    metrics = json.loads((REPORTS / "metrics.json").read_text())
    generation = json.loads((REPORTS / "generation_metrics.json").read_text())

    df = load_raw()
    n_total = len(df)
    labels = df["isFraud"].to_numpy(dtype=np.float64)

    # x is normalised TransactionDT over the FULL range, so a point's horizontal
    # position is its real time. y is log10 rupees over the full range.
    dt = df["TransactionDT"].to_numpy(dtype=np.float64)
    x_all = (dt - dt.min()) / (dt.max() - dt.min())
    amounts_inr = to_inr(df["TransactionAmt"].to_numpy(dtype=np.float64))
    if amounts_inr.min() <= 0:
        raise SystemExit("a non-positive transaction amount has no log10")
    log_amt = np.log10(amounts_inr)
    y_all = (log_amt - log_amt.min()) / (log_amt.max() - log_amt.min())

    # Scored once, over the whole frame. build_features is row-wise and the
    # category sets are fixed at training time, so a slice of this array is
    # identical to scoring that slice on its own -- and one pass is cheaper than
    # three. The PR-AUC check below is what proves the slice is the right one.
    p_all = scorer.score_batch(df)

    idx, sampling = _stratified_sample(labels)
    points = np.column_stack(
        [x_all[idx], y_all[idx], p_all[idx], labels[idx]]
    ).astype(np.float32)

    # Split geometry. The boundaries come from the real splitter's own output,
    # not from re-implementing its arithmetic here.
    train, calib, test = temporal_split(df)
    i_train, i_calib = len(train), len(train) + len(calib)
    del train, calib

    # THE SPLIT DOES NOT LAND AT x = 0.70. TRAIN_FRAC is a fraction of ROWS and
    # x is a fraction of TIME, and transaction density is not uniform: 74.2% of
    # rows fall left of x = 0.70. Planes drawn at 0.70 and 0.80 would sit in the
    # wrong place and the section would explain the split by mis-drawing it. So
    # train_end_x and calib_end_x are the measured x of the real row boundaries,
    # and the row fractions are reported beside them under their own names.
    split = {
        "train_end_x": float(x_all[i_train]),
        "calib_end_x": float(x_all[i_calib]),
        "train_frac": TRAIN_FRAC,
        "calib_frac": CALIB_FRAC,
        # Measured off the splitter's own row counts. Adding TRAIN_FRAC and
        # CALIB_FRAC in IEEE-754 gives 0.7999999999999999, which is the same
        # trap split.py documents in its own boundary arithmetic.
        "train_end_row_frac": i_train / n_total,
        "calib_end_row_frac": i_calib / n_total,
        "train_rows": int(i_train),
        "calib_rows": int(i_calib - i_train),
        "test_rows": int(n_total - i_calib),
        "basis": "70/10/20 by row count on TransactionDT order. train_end_x and "
                 "calib_end_x are where those row boundaries fall on the "
                 "normalised time axis the point cloud is drawn on.",
    }

    y_test = test["isFraud"].to_numpy()
    p_test = p_all[i_calib:]
    del test, df

    from sklearn.calibration import calibration_curve
    from sklearn.metrics import average_precision_score, precision_recall_curve

    # The curves must describe the same population family A reports, or the site
    # would draw one model and quote another.
    replayed_pr_auc = float(average_precision_score(y_test, p_test))
    if abs(replayed_pr_auc - metrics["family_a"]["pr_auc"]) > 1e-9:
        raise SystemExit(
            f"PR-AUC recomputed here is {replayed_pr_auc} but "
            f"eval/reports/metrics.json says {metrics['family_a']['pr_auc']}. "
            f"The artifacts and the report disagree; re-run `python -m eval.run_eval`."
        )

    precision, recall, _ = precision_recall_curve(y_test, p_test)
    frac_pos, mean_pred = calibration_curve(y_test, p_test, n_bins=10,
                                            strategy="quantile")

    demo = load_raw(sample_n=DEMO_SAMPLE_N)
    vault = VaultStore()
    cases = {
        name: (_case(name, row, demo, scorer, vault) if row is not None else None)
        for name, row in DEMO_ROWS.items()
    }
    refusal = _refusal(DEMO_ROWS["contest"], demo, scorer, vault)

    snapshot = {
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "n_total": int(n_total),
        "n_sampled": int(len(idx)),
        "sampling": sampling,
        "split": split,
        "family_a": metrics["family_a"],
        "family_b": metrics["family_b"],
        "family_c": generation,
        "curves": {
            "pr": _downsample(recall, precision),
            "calibration": _downsample(mean_pred, frac_pos),
        },
        "cases": cases,
        "refusal": refusal,
        "notes": {
            "accept_case": (
                "There is no ACCEPT case because no ACCEPT decision was "
                "reachable when these rows were selected. ACCEPT needs ACTIVE "
                "posture, which takes a large expected exposure, together with "
                "an expected value below the negative margin, which takes a "
                "small amount. The rows satisfying both are ProductCD C and S, "
                "and those products never record the M1/M2/M6 address-match "
                "flags. With no flags synthesize_casefile files no "
                "billing_proof, billing_proof is required for "
                "fraud_card_absent, and the evidence gate returns REVIEW before "
                "expected value is consulted. Recheck with "
                "`python -m eval.find_demo_rows`."
            ),
            "points": (
                "A stratified sample of the dataset, not the whole of it. The "
                "headline count is 590,540; this buffer holds 100,000."
            ),
        },
    }

    SITE_DATA_DIR.mkdir(parents=True, exist_ok=True)
    (SITE_DATA_DIR / "points.bin").write_bytes(points.tobytes())
    (SITE_DATA_DIR / "snapshot.json").write_text(json.dumps(snapshot, indent=2))

    print(f"points.bin      {points.shape[0]} points x 4 float32 = "
          f"{(SITE_DATA_DIR / 'points.bin').stat().st_size} bytes")
    print(f"snapshot.json   {(SITE_DATA_DIR / 'snapshot.json').stat().st_size} bytes")
    print(f"keys            {sorted(snapshot)}")
    print(f"split           {split['train_end_x']:.4f} / {split['calib_end_x']:.4f}")
    print(f"curves          pr={len(snapshot['curves']['pr'])} "
          f"calibration={len(snapshot['curves']['calibration'])}")
    print(f"cases           " + ", ".join(
        f"{k}={v['decision']['action'] if v else 'UNAVAILABLE'}"
        for k, v in cases.items()))
    print(f"refusal         {refusal['before']} -> {refusal['after']}, "
          f"groundedness {refusal['groundedness']:.4f}")
    return snapshot


if __name__ == "__main__":
    main()
